/**
 * RIFAH Centralized Business Categories & Sub-Categories Taxonomy
 * Comprehensive dataset of 500+ industry classifications and specialized business activities.
 */

export const CATEGORIES_DATA = {
  "Information Technology & Software (IT)": [
    "Web Development & Design",
    "Mobile App Development (iOS & Android)",
    "Cloud Computing & DevOps",
    "Artificial Intelligence & Machine Learning",
    "Cybersecurity & Information Security",
    "SaaS Product Development",
    "IT Consulting & System Integration",
    "Database Administration & Big Data",
    "ERP & CRM Solutions (SAP, Oracle)",
    "UI/UX Design & Prototyping",
    "E-Commerce Development (Shopify, Magento)",
    "Blockchain & Web3 Technologies",
    "Quality Assurance & Software Testing",
    "Data Analytics & Business Intelligence",
    "IoT (Internet of Things) Solutions",
    "IT Infrastructure & Networking",
    "API & Microservices Development",
    "Embedded Systems & Firmware",
    "Game Development & AR/VR",
    "Managed IT Services & Helpdesk",
    "Disaster Recovery & Backup Solutions",
    "Technical Support & Maintenance",
    "Web Hosting & Domain Services",
    "IT Hardware & Server Management"
  ],

  "Manufacturing & Industrial Production": [
    "CNC Machining & Precision Engineering",
    "Plastic Injection Moulding",
    "Sheet Metal Fabrication",
    "Industrial Machinery & Equipment",
    "Die Casting & Foundry",
    "Tool & Die Making",
    "Automation & Robotics Manufacturing",
    "Hydraulic & Pneumatic Systems",
    "Rubber & Polymer Products",
    "Glass & Ceramic Manufacturing",
    "Fasteners, Bolts & Industrial Hardware",
    "Boiler & Pressure Vessel Fabrication",
    "Pumps & Valves Manufacturing",
    "Conveyor & Material Handling Systems",
    "Laser Cutting & Metal Forming",
    "Leather Goods Manufacturing",
    "Cable Tray & Enclosure Manufacturing",
    "Heat Treatment & Surface Finishing",
    "Heavy Engineering & Fabrication",
    "Assembly Line & Custom Machinery",
    "Woodworking & Timber Manufacturing",
    "Industrial Filters & Filtration Systems",
    "Bearings & Power Transmission",
    "Paints & Coating Equipment"
  ],

  "Healthcare, Pharmaceuticals & Medical": [
    "Hospitals & Multi-Specialty Clinics",
    "Pharmaceutical Formulations & Drugs",
    "Active Pharmaceutical Ingredients (API)",
    "Medical Diagnostic Labs & Pathology",
    "Medical Devices & Surgical Instruments",
    "Ayurvedic & Herbal Medicines",
    "Dental Clinics & Oral Care Equipment",
    "Home Healthcare & Nursing Services",
    "Physiotherapy & Rehabilitation",
    "Ophthalmic & Vision Care Centers",
    "Biotechnology & Clinical Research",
    "Medical Oxygen & Gas Systems",
    "Orthopedic Implants & Prosthetics",
    "Radiology & Imaging Centers",
    "Wellness & Preventive Healthcare",
    "Health Insurance & Third-Party Admin",
    "Veterinary Healthcare & Medicines",
    "Pharmacy Chains & Retail Chemist",
    "Medical Waste Management",
    "Hospital Furniture & Infrastructure",
    "Telemedicine & Digital Health",
    "Critical Care & Ambulance Services",
    "Nutraceuticals & Dietary Supplements",
    "Disinfectants & Hospital Sanitization"
  ],

  "Textiles, Garments & Fashion Apparel": [
    "Cotton Yarn & Spinning Mills",
    "Fabric Weaving & Knitting",
    "Ready-Made Garments & Apparel",
    "Menswear & Formal Clothing",
    "Womenswear & Ethnic Clothing",
    "Children & Infant Clothing",
    "Textile Dyeing, Printing & Finishing",
    "Denims & Jeanswear",
    "Home Textiles (Bedsheets, Curtains)",
    "Technical & Medical Textiles",
    "Embroidery & Zari Work",
    "Silk & Synthetic Fabrics",
    "Woolen & Knitted Garments",
    "Innerwear & Hosiery Products",
    "Uniforms & Workwear",
    "Sportswear & Activewear",
    "Tailoring & Bespoke Stitching",
    "Sewing Threads & Trims",
    "Carpet, Rugs & Mat Manufacturing",
    "Fashion Accessories & Belts",
    "Garment Export & Buying House",
    "Non-Woven Fabric & Geotextiles",
    "Leather & Faux Leather Garments",
    "Abayas, Hijabs & Modest Wear"
  ],

  "Construction, Architecture & Real Estate": [
    "Civil Contracting & Infrastructure",
    "Architectural Design & Planning",
    "Residential Building Construction",
    "Commercial Complex & Mall Construction",
    "Interior Design & Fit-Outs",
    "Structural Engineering & Consulting",
    "Real Estate Broking & Advisory",
    "Ready-Mix Concrete (RMC) Supply",
    "Tiles, Marble & Granite Stone",
    "Plumbing & Sanitary Contracting",
    "Electrical Contracting & Wiring",
    "Waterproofing & Insulation Services",
    "Painting, False Ceiling & Wallpapers",
    "Property Management & Maintenance",
    "Land Surveying & Soil Testing",
    "Aluminum & Glass Glazing Work",
    "Scaffolding & Shuttering Services",
    "Demolition & Earthmoving Contractors",
    "HVAC (Central AC) Installation",
    "Fire Fighting Systems & Sprinklers",
    "Swimming Pool Design & Construction",
    "Road, Pavement & Bridge Contracting",
    "Modular Kitchen & Wardrobe Systems",
    "Fencing & Boundary Wall Solutions"
  ],

  "Food, Beverages & FMCG": [
    "Packaged Foods & Ready-to-Eat",
    "Dairy Products (Milk, Cheese, Ghee)",
    "Bakery & Confectionery",
    "Spices, Seasonings & Masalas",
    "Tea & Coffee Processing",
    "Edible Oils & Ghee Refining",
    "Snacks, Namkeen & Savouries",
    "Bottled Water & Soft Drinks",
    "Fruit Juices & Beverage Processing",
    "Organic & Health Foods",
    "Flour Mills & Atta Processing",
    "Rice Milling & Pulses Processing",
    "Sugar & Sweeteners Manufacturing",
    "Frozen Foods & Cold Chain Storage",
    "Sauces, Jams, Pickles & Condiments",
    "Confectionery, Chocolates & Sweets",
    "Meat, Poultry & Seafood Processing",
    "Halal Food Products",
    "Catering & Banquet Services",
    "Cloud Kitchens & Food Delivery",
    "Food Ingredients & Food Additives",
    "Dry Fruits & Nuts Processing",
    "Ice Cream & Frozen Desserts",
    "Honey & Natural Sweeteners"
  ],

  "Agriculture, Farming & Dairy": [
    "Organic Farming & Produce",
    "Seeds & Hybrid Cultivation",
    "Fertilizers & Bio-Nutrients",
    "Pesticides & Plant Protection",
    "Micro-Irrigation & Drip Systems",
    "Greenhouse & Polyhouse Farming",
    "Poultry Farming & Hatcheries",
    "Dairy Farming & Cattle Breeding",
    "Aquaculture & Fish Farming",
    "Farm Machinery & Tractor Implements",
    "Horticulture & Floriculture",
    "Hydroponics & Vertical Farming",
    "Cold Storage & Warehousing of Agro",
    "Grain Storage & Silos",
    "Animal Feed & Fodder Production",
    "Beekeeping & Honey Production",
    "Agro Forestry & Plantation",
    "Post-Harvest Management",
    "Soil Testing & Crop Advisory",
    "Solar Water Pumps for Farming",
    "Sericulture & Silk Production",
    "Herbal & Medicinal Plant Farming",
    "Mushroom Cultivation",
    "Agricultural Drone Services"
  ],

  "Automotive, Electric Vehicles & Auto Parts": [
    "Commercial Vehicle Dealerships",
    "Passenger Car Dealerships",
    "Two-Wheeler & Three-Wheeler Dealerships",
    "Electric Vehicle (EV) Manufacturing",
    "EV Charging Stations & Infrastructure",
    "Automotive Sheet Metal Stampings",
    "Engine Components & Transmission",
    "Auto Electricals & Wiring Harnesses",
    "Car Accessories & Seat Covers",
    "Automobile Service & Repair Garages",
    "Fleet Management & GPS Tracking",
    "Tyres, Tubes & Retreading",
    "Auto Glass & Windshield Replacement",
    "Batteries & Lead Acid / Li-Ion Units",
    "Radiators & Cooling Systems",
    "Brake Linings, Discs & Pads",
    "Suspension & Steering Parts",
    "Second Hand / Pre-Owned Cars",
    "Vehicle Body Building & Fabrication",
    "Car Wash & Detailing Studios",
    "CNG / LPG Conversion Kits",
    "Automobile Leasing & Rentals",
    "Bicycle & E-Bike Manufacturing",
    "Auto Paints & Body Shop Supplies"
  ],

  "Banking, Islamic Finance & Fintech": [
    "Islamic Banking & Shariah Advisory",
    "Commercial & Retail Banking",
    "Microfinance & SHG Lending",
    "NBFCs & Business Loans",
    "Payment Gateway & POS Terminals",
    "Wealth Management & Financial Planning",
    "Stock Broking & Equity Trading",
    "Mutual Funds & SIP Advisory",
    "General & Health Insurance Broking",
    "Life Insurance & Takaful",
    "Fintech Mobile Apps & Wallets",
    "Peer-to-Peer (P2P) Lending",
    "Foreign Exchange (Forex) & Remittances",
    "Chartered Accountancy & Tax Advisory",
    "GST & Income Tax Return Filing",
    "Auditing & Assurance Services",
    "Company Secretarial & ROC Filing",
    "Trade Finance & Letters of Credit",
    "Debt Recovery & Restructuring",
    "Venture Capital & Angel Investment",
    "Halal Investment Portfolios",
    "Crowdfunding & Charity Finance",
    "Cryptocurrency & Digital Assets",
    "Financial Risk Consulting"
  ],

  "Retail, E-Commerce & Wholesale Trading": [
    "Supermarkets & Grocery Chains",
    "Departmental Stores & Malls",
    "Consumer Electronics Retail",
    "Footwear & Luggage Retail",
    "Hardware & Sanitaryware Stores",
    "Kirana & Mom-and-Pop Retail",
    "B2B E-Commerce Marketplace",
    "Direct-to-Consumer (D2C) Brands",
    "Furniture & Home Décor Showrooms",
    "Mobile Phones & Gadget Stores",
    "Books & Stationery Stores",
    "Toy Stores & Baby Products",
    "Optical & Eyewear Showrooms",
    "Watch & Clock Retail",
    "Sports Goods & Fitness Equipment",
    "General Trading & Import-Export",
    "Dropshipping & Fulfillment Services",
    "Wholesale Commodity Trading",
    "Uniform & Safety Equipment Supply",
    "Cosmetics & Personal Care Stores",
    "Kitchenware & Crockery Retail",
    "Flea Market & Pop-up Stores",
    "Pet Care & Pet Supplies Retail",
    "Music Instruments & Audio Gear"
  ],

  "Education, Training & EdTech": [
    "K-12 Schools & Play Schools",
    "Colleges & Higher Education Institutes",
    "Coaching Institutes (IIT-JEE, NEET, UPSC)",
    "Vocational & Skill Development Centers",
    "Online Learning Platforms & EdTech",
    "Professional Certification Courses",
    "Language Learning & IELTS Institutes",
    "Computer & Coding Academies",
    "Corporate Training & Soft Skills",
    "Madrasas & Islamic Education Centers",
    "Aviation & Hospitality Academies",
    "Study Abroad & Visa Consulting",
    "Special Needs & Inclusive Education",
    "Montessori & Nursery Teacher Training",
    "Distance Education & Universities",
    "Music, Dance & Fine Arts Schools",
    "Educational Toy & Book Publishers",
    "Career Counseling & Psychometric Testing",
    "Laboratory Equipment for Schools",
    "School Uniform & Supply Vendors",
    "Campus Recruitment & Placement Firms",
    "Sports Coaching & Athletics Academies",
    "Robotics & STEM Labs for Kids",
    "Leadership & Executive Development"
  ],

  "Professional, Legal & Accounting Services": [
    "Corporate Law & Litigation",
    "Intellectual Property & Patent Filings",
    "Chartered Accountants & Tax Consultants",
    "Company Secretaries (CS)",
    "Cost & Management Accountants",
    "Human Resource & Staffing Agencies",
    "Management & Strategy Consulting",
    "Business Valuation & Mergers",
    "Labour Law Compliance & EPF/ESIC",
    "Notary & Document Attestation",
    "Arbitration & Mediation Services",
    "Risk & Fraud Investigation",
    "Market Research & Feasibility Studies",
    "Translation & Interpretation Services",
    "Environmental Impact Assessment",
    "ISO Certification & Auditing",
    "Trademark & Copyright Registration",
    "Cyber Law & Data Privacy Advisory",
    "Virtual CFO & Bookkeeping Services",
    "Secretarial Audits & Due Diligence",
    "Visa & Immigration Legal Services",
    "Executive Coaching & Leadership",
    "Business Process Outsourcing (BPO)",
    "Document Archiving & Storage"
  ],

  "Logistics, Supply Chain & Warehousing": [
    "Road Freight & Truck Transportation",
    "Express Courier & Parcel Delivery",
    "Ocean Freight & Container Shipping",
    "Air Cargo & Freight Forwarding",
    "Cold Storage & Refrigerated Vans",
    "Bonded Warehousing & 3PL Logistics",
    "Customs House Clearance (CHA)",
    "Last-Mile Delivery Services",
    "Packers & Movers (Relocation)",
    "Fleet Management & Vehicle Tracking",
    "Pallets, Racks & Storage Systems",
    "Port Handling & Stevedoring",
    "Intermodal & Rail Cargo Services",
    "Dangerous Goods (HAZMAT) Transport",
    "E-Commerce Fulfillment Warehouses",
    "Reverse Logistics & Returns Handling",
    "Bulk Cargo & Tanker Transport",
    "Crane & Heavy Equipment Rental",
    "Cargo Insurance & Claims Handling",
    "Supply Chain Software & TMS",
    "Temperature-Controlled Logistics",
    "Local Tempo & Mini-Truck Services",
    "Container Repair & Maintenance",
    "Distribution Center Operations"
  ],

  "Electrical, Electronics & Hardware": [
    "Industrial Electrical Switchgear",
    "Power Transformers & Substations",
    "Electric Motors & Generators",
    "LED Lighting & Luminaires",
    "Wires, Cables & Conduits",
    "Solar Inverters & Batteries",
    "Printed Circuit Boards (PCB Assembly)",
    "Electronic Components & Semiconductors",
    "Home Automation & Smart Devices",
    "CCTV & Electronic Surveillance",
    "Fire Alarm & Detection Systems",
    "Control Panels & PLC Automation",
    "Hand Tools & Power Tools",
    "Test & Measurement Instruments",
    "Consumer Appliances (Fridges, TVs, ACs)",
    "Uninterruptible Power Supply (UPS)",
    "Copper & Aluminum Busbars",
    "Electric Fans & Air Coolers",
    "Electronic Weighing Scales",
    "Audio-Visual & Public Address Systems",
    "Enclosures & Electrical Junction Boxes",
    "Earthing & Lightning Protection Systems",
    "Sensors & Transducers",
    "Industrial Plugs & Sockets"
  ],

  "Chemicals, Petrochemicals & Polymers": [
    "Specialty & Fine Chemicals",
    "Industrial Solvents & Thinners",
    "Agrochemicals & Crop Protection",
    "Polymers & Plastic Raw Materials (Granules)",
    "Resins, Adhesives & Sealants",
    "Paints, Varnishes & Coatings",
    "Dyes, Pigments & Colorants",
    "Water Treatment Chemicals",
    "Petrochemical By-Products",
    "Industrial Gases (Oxygen, Nitrogen, CO2)",
    "Lubricants, Greases & Engine Oils",
    "Cleaning & Disinfection Chemicals",
    "Flavours & Fragrance Chemicals",
    "Textile Auxiliaries & Processing Chemicals",
    "Construction Chemicals & Admixtures",
    "Laboratory Reagents & Chemicals",
    "Fertilizer Raw Materials (Urea, DAP)",
    "Rubber Processing Chemicals",
    "Electroplating & Metal Treatment Chemicals",
    "Oleochemicals & Natural Oils",
    "Polyurethane Foam & Insulation",
    "Synthetic Fibers & Monofilament",
    "Catalysts & Chemical Intermediates",
    "Silicone & Release Agents"
  ],

  "Media, Advertising & Digital Marketing": [
    "Search Engine Optimization (SEO)",
    "Pay-Per-Click (PPC) & Google Ads",
    "Social Media Marketing & Management",
    "Content Creation & Copywriting",
    "Video Production & Commercial Ads",
    "Graphic Design & Brand Identity",
    "Public Relations (PR) Agencies",
    "Influencer Marketing & Talent Management",
    "Billboard & Outdoor (OOH) Advertising",
    "Event Management & Conferences",
    "Photography & Studio Shoots",
    "Animation & Motion Graphics",
    "Podcast & Audio Production",
    "Print Media & Magazine Publishing",
    "Radio & FM Advertising",
    "TV & OTT Commercials",
    "Website UI/UX Design & Landing Pages",
    "Email Marketing & Automation",
    "Exhibition Stall Design & Fabrication",
    "Media Buying & Planning",
    "Brand Strategy & Consultation",
    "Digital Signage & LED Video Walls",
    "Influencer Agency & Creator Network",
    "Celebrity Management & Endorsements"
  ],

  "Hospitality, Travel & Tourism": [
    "Hotels, Resorts & Homestays",
    "Haj & Umrah Tour Operators",
    "Domestic Tour Packages & Sightseeing",
    "International Holidays & Tours",
    "Airline Ticketing & Flight Bookings",
    "Visa Processing & Passport Assistance",
    "Car & Coach Rentals",
    "Travel Insurance Services",
    "Restaurants, Cafes & Fine Dining",
    "Banquet Halls & Wedding Venues",
    "Houseboats & Cruise Bookings",
    "Adventure Tourism & Trekking",
    "Corporate Offsite & MICE Organizers",
    "Airport Lounge & Protocol Services",
    "Bed & Breakfast / Hostels",
    "Eco-Tourism & Wildlife Safaris",
    "Food Trucks & Pop-up Kiosks",
    "Bakeries, Patisseries & Dessert Bars",
    "Heritage Hotels & Forts",
    "Tourist Guides & Escorted Tours",
    "Luxury Car Rentals for Weddings",
    "Travel Forex & Currency Exchange",
    "Campground & Glamping Resorts",
    "Travel Agency Franchise Networks"
  ],

  "Renewable Energy, Solar & Environment": [
    "Rooftop Solar PV Systems",
    "Ground-Mounted Solar Power Plants",
    "Solar Inverters & Micro-Inverters",
    "Solar Street Lighting & Home Lighting",
    "Solar Water Heaters",
    "Wind Turbine Energy & Parts",
    "Biogas & Bio-CNG Plants",
    "Battery Energy Storage Systems (BESS)",
    "EV Charging Stations",
    "Waste Management & Recycling",
    "Effluent Treatment Plants (ETP)",
    "Sewage Treatment Plants (STP)",
    "Water Desalination Systems",
    "Hazardous Waste Disposal",
    "Plastic Waste Upcycling & Recycling",
    "E-Waste Recycling & Refurbishing",
    "Air Quality Monitoring & Scrubbers",
    "Carbon Credit & Sustainability Consulting",
    "Green Building Consulting (LEED / IGBC)",
    "Rainwater Harvesting Systems",
    "Biomass Briquettes & Pellets",
    "Energy Auditing & Conservation Services",
    "Geothermal & Hydroelectric Systems",
    "Solid Waste Incineration & Composting"
  ],

  "Metals, Mining & Metallurgy": [
    "Mild Steel (MS) TMT Bars & Structural Steel",
    "Stainless Steel (SS) Sheets, Pipes & Tubes",
    "Aluminum Extrusions & Ingots",
    "Copper Cathodes, Wires & Rods",
    "Brass, Bronze & Copper Alloys",
    "Iron Ore, Coal & Mineral Trading",
    "Steel Forging & Castings",
    "Scrap Metal Recycling (Ferrous & Non-Ferrous)",
    "Metal Corrugated Roofing Sheets",
    "Wire Mesh, Barbed Wire & Chain Link",
    "Zinc & Galvanized Steel Coils",
    "Steel Pipes, ERW & Seamless Tubes",
    "Metal Slitting, Cutting & Blanking",
    "Sand, Aggregates & Stone Quarrying",
    "Granite, Marble & Quartz Blocks",
    "Lead & Battery Recycling",
    "Metal Stamping & Deep Drawing",
    "Mining Machinery & Excavation Equipment",
    "Precious Metal Refining (Gold, Silver)",
    "Industrial Scaffolding Pipes & Clamps",
    "Titanium & Specialty Alloy Stockists",
    "Metal Surface Polishing & Electroplating",
    "Wire Rods & Bright Bars",
    "Industrial Flanges & Pipe Fittings"
  ],

  "Printing, Packaging & Paper Products": [
    "Corrugated Boxes & Cartons",
    "Flexible Packaging & Pouches",
    "Offset Commercial Printing",
    "Digital Printing & Large Format Banners",
    "Self-Adhesive Labels & Stickers",
    "Monocartons & Rigid Luxury Boxes",
    "Paper Bags & Eco-Friendly Packaging",
    "Biodegradable Packaging Solutions",
    "Wooden Pallets & Crates",
    "Shrink Film, Stretch Wrap & Strapping",
    "Tin Cans & Metal Packaging",
    "Glass Bottles & Jars",
    "Plastic Bottles, Jars & Caps",
    "Thermal Paper & POS Rolls",
    "Books, Notebooks & Diary Printing",
    "Security Printing (Holograms, Barcodes)",
    "Packaging Design & Pre-Press",
    "Tissue Paper & Disposable Products",
    "Kraft Paper & Duplex Board Manufacturing",
    "Lamination & Foil Stamping Services",
    "Blister Packaging & Vacuum Forming",
    "Courier Bags & Tamper-Evident Envelopes",
    "Air Bubble & Foam Protective Packaging",
    "Carton Sealing Tapes & Adhesives"
  ],

  "Gems, Jewellery & Luxury Goods": [
    "Gold Jewellery Manufacturing",
    "Diamond Jewellery & Studded Ornaments",
    "Silver Ornaments & Utensils",
    "Loose Diamonds & Gemstones",
    "Kundan, Polki & Antique Jewellery",
    "Imitation & Fashion Jewellery",
    "Bridal Jewellery & Rental Sets",
    "Luxury Watches & Horology",
    "Pearls & Coral Trading",
    "Hallmarking & Assay Centers",
    "CAD/CAM Jewellery Designing",
    "Jewellery Boxes & Display Displays",
    "Gemological Testing Laboratories",
    "Diamond Cutting & Polishing",
    "Gold Coins & Bullion Trading",
    "Platinum Jewellery",
    "Customized Bespoke Jewellery",
    "Jewellery Repair, Cleaning & Polishing",
    "Sterling Silver 925 Gifts & Articles",
    "Fashion Accessories & Cufflinks",
    "Perfumes, Attars & Luxury Fragrances",
    "High-End Handbags & Leather Goods",
    "Precious Stones Appraisal",
    "Gemstone Carving & Inlay Art"
  ],

  "Security, Facilities Management & Cleaning": [
    "Manned Security Guard Services",
    "Bouncers & Personal Bodyguards",
    "CCTV & Electronic Surveillance Setup",
    "Access Control & Biometric Systems",
    "Fire Alarm & Detection Systems",
    "Fire Extinguisher Refilling & Maintenance",
    "Commercial Housekeeping & Janitorial",
    "Deep Cleaning Services (Homes & Offices)",
    "Pest Control & Disinfection",
    "Waste Disposal & Garbage Collection",
    "Facility Management & AMC Contracts",
    "Building Facade Cleaning",
    "Valet Parking & Traffic Marshals",
    "Corporate Reception & Front Desk Staffing",
    "Landscape Maintenance & Gardening",
    "Water Tank Cleaning & Sanitization",
    "Carpet & Sofa Shampooing",
    "Cash-in-Transit (CIT) Vans & Armed Guards",
    "Metal Detectors & Baggage Scanners",
    "Smart Keyless Locks & Perimeter Fencing",
    "Guard Patrol Monitoring Systems",
    "Air Duct Cleaning & Kitchen Exhaust Degreasing",
    "Disaster Management & Emergency Response",
    "Swimming Pool Cleaning & Maintenance"
  ]
};

// Return array of all main category names
export function getMainCategories() {
  return Object.keys(CATEGORIES_DATA);
}

// Return array of subcategories for a given category name (case-insensitive & fuzzy match)
export function getSubCategoriesFor(categoryName) {
  if (!categoryName) return [];
  const trimmed = categoryName.trim().toLowerCase();
  
  // 1. Direct exact or lower-case match
  for (const [cat, subs] of Object.entries(CATEGORIES_DATA)) {
    if (cat.toLowerCase() === trimmed) {
      return subs;
    }
  }

  // 2. Partial/fuzzy match (e.g. if category is "IT" or "Information Technology")
  for (const [cat, subs] of Object.entries(CATEGORIES_DATA)) {
    const cLower = cat.toLowerCase();
    if (cLower.includes(trimmed) || trimmed.includes(cLower)) {
      return subs;
    }
    // Also check abbreviation like "IT"
    if (trimmed === "it" && cLower.includes("information technology")) {
      return subs;
    }
  }

  return [];
}

// Generate flat list of all categories and subcategories with parent and slug
export function getAllFlatCategories() {
  const result = [];
  const slugify = (text) =>
    text
      .toString()
      .toLowerCase()
      .trim()
      .replace(/[\s\W-]+/g, "-")
      .replace(/^-+|-+$/g, "");

  for (const [catName, subList] of Object.entries(CATEGORIES_DATA)) {
    result.push({
      name: catName,
      slug: slugify(catName),
      parent: "",
      status: "Active"
    });

    for (const subName of subList) {
      result.push({
        name: subName,
        slug: slugify(`${catName}-${subName}`),
        parent: catName,
        status: "Active"
      });
    }
  }

  return result;
}
